// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkib5A4t0y3xxwaeDE1RTvv0lOhQiDtaE',
    appId: '1:458681307305:web:a8ae78c577b6c0cff919b8',
    messagingSenderId: '458681307305',
    projectId: 'chatapp-b0454',
    authDomain: 'chatapp-b0454.firebaseapp.com',
    storageBucket: 'chatapp-b0454.appspot.com',
    measurementId: 'G-ZQGLNZ2MS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa2GoIdlbFGvVe6dMTRI9zFquCdz--R7I',
    appId: '1:458681307305:android:880bae542369ff48f919b8',
    messagingSenderId: '458681307305',
    projectId: 'chatapp-b0454',
    storageBucket: 'chatapp-b0454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuswCT1pIb8NQvItbfw0NFvJc0NK-tkXI',
    appId: '1:458681307305:ios:6425bec88fe8eeb6f919b8',
    messagingSenderId: '458681307305',
    projectId: 'chatapp-b0454',
    storageBucket: 'chatapp-b0454.appspot.com',
    iosBundleId: 'com.example.appzs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuswCT1pIb8NQvItbfw0NFvJc0NK-tkXI',
    appId: '1:458681307305:ios:aec928bcac7bc87cf919b8',
    messagingSenderId: '458681307305',
    projectId: 'chatapp-b0454',
    storageBucket: 'chatapp-b0454.appspot.com',
    iosBundleId: 'com.example.appzs.RunnerTests',
  );
}
